### ISSUE TITLE
AttributeError after upgrade from cbapi version 1.2.0 to 1.3.4

### ISSUE THREAD

**Issue by naes17** [carbonblack/cbapi-python#84]
After upgrading to the new version, I get the following Attribute error when trying to call the unsigned_modloads method on a process object.

When I reverted back to cbapi version 1.2.0 it started working again.

    for unmodload in proc.unsigned_modloads:
  File "../python3.4/site-packages/cbapi/oldmodels.py", line 131, in __getattr__
    return super(BaseModel, self).__getattribute__(attrname)
  File "../python3.4/site-packages/cbapi/response/models.py", line 2356, in unsigned_modloads
    return [m for m in self.modloads if not m.is_signed]
  File "../python3.4/site-packages/cbapi/response/models.py", line 2356, in <listcomp>
    return [m for m in self.modloads if not m.is_signed]
  File "../python3.4/site-packages/cbapi/response/models.py", line 2825, in is_signed
    return False if (not(self.binary.signed) or self.binary.is_signed == '(Unknown)') else True
  File "../python3.4/site-packages/cbapi/oldmodels.py", line 131, in __getattr__
    return super(BaseModel, self).__getattribute__(attrname)
AttributeError: 'Binary' object has no attribute 'is_signed'

**Comment by jgarman** [comment]
Thanks for the report- sorry about that. It'll be fixed in the next version which will be released this week.
