### ISSUE TITLE
cbapi release 1.5.0 fails to import in python (2.7, 3.6)

### ISSUE THREAD

**Issue by fslds** [carbonblack/cbapi-python#173]
The latest PyPi release of [cbapi 1.5.0 (released July 31st)](https://pypi.org/project/cbapi/1.5.0) fails to import both in python 3.6 as in python 2.7 with different errors, rendering it useless. This can and will break automated setups where they did not 'pin' versions. (`cbapi==1.4.5`)

## Steps to reproduce:
`pip install cbapi`
### Python 2.7
```python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cbapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home//.virtualenvs/cbapi2/local/lib/python2.7/site-packages/cbapi/__init__.py", line 12, in <module>
    from cbapi.response.rest_api import CbEnterpriseResponseAPI, CbResponseAPI
  File "/home/bobsyouruncle/.virtualenvs/cbapi2/local/lib/python2.7/site-packages/cbapi/response/__init__.py", line 9, in <module>
    from .rest_api import CbEnterpriseResponseAPI, CbResponseAPI
  File "/home/bobsyouruncle/.virtualenvs/cbapi2/local/lib/python2.7/site-packages/cbapi/response/rest_api.py", line 12, in <module>
    from .cblr import LiveResponseSessionManager
  File "/home/bobsyouruncle/.virtualenvs/cbapi2/local/lib/python2.7/site-packages/cbapi/response/cblr.py", line 1, in <module>
    from cbapi.live_response_api import CbLRManagerBase, CbLRSessionBase, poll_status
  File "/home/bobsyouruncle/.virtualenvs/cbapi2/local/lib/python2.7/site-packages/cbapi/live_response_api.py", line 15, in <module>
    from concurrent.futures import ThreadPoolExecutor, as_completed, _base, wait
ImportError: No module named concurrent.futures
```

### Python 3.6
```python
Python 3.6.9 (default, Jul  3 2019, 15:36:16) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cbapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bobsyouruncle/.virtualenvs/cbapi3/lib/python3.6/site-packages/cbapi/__init__.py", line 16, in <module>
    from cbapi.psc.livequery import CbLiveQueryAPI
ImportError: cannot import name 'CbLiveQueryAPI'
```

**Comment by punkrokk** [comment]
I am experiencing the same behavior.

**Comment by slw07g** [comment]
commenting out the line `from cbapi.psc.livequery import CbLiveQueryAPI` in `site-packages/cbapi/__init__.py"` allowed me to work around it in the mean time.

**Comment by smultani** [comment]
@fslds, @punkrokk, @slw07g - thanks for bringing this issue up. 

We fixed the issue and shipped CBAPI v1.5.1 on 08/05/2019. 

Thank you!

**Comment by fslds** [comment]
Thank you! now works in Python 3.6, however, python 2.7 still fails.
` pip install cbapi==1.5.1`


```
